/*
 *   This file was AUTO-GENERATED by pypgmopts.
 *
 *   https://github.com/johndoe31415/pypgmopts
 *
 *   Do not edit it by hand, your changes will be overwritten.
 *
 *   Generated at: 2018-09-02 14:23:16
 */

#ifndef __ARGPARSE_H__
#define __ARGPARSE_H__

#include <stdbool.h>

enum argparse_option_t {
	ARG_UNIX_SOCKET,
};

typedef bool (*argparse_callback_t)(enum argparse_option_t option, const char *value);

bool argparse_parse(int argc, char **argv, argparse_callback_t argument_callback);
void argparse_show_syntax(void);
void argparse_parse_or_die(int argc, char **argv, argparse_callback_t argument_callback);

#endif
